version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mochisuna
  assignees:
  - mochisuna
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
  - dependency-name: cloud.google.com/go
    versions:
    - 0.75.0
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.80.0
  - dependency-name: github.com/unrolled/render
    versions:
    - 1.0.3
  - dependency-name: github.com/go-chi/cors
    versions:
    - 1.1.1
